### ISSUE TITLE
Mobile needs some tweaking

### ISSUE THREAD

**Issue by Baertie** [threefoldtech/twin_aydo#626]
- [x] Share flow post doesn't allow sharing [https://github.com/threefoldtech/twin_aydo/issues/616](url)
- [x] Whisper name overlaps with profile image [https://github.com/threefoldtech/twin_aydo/issues/615](url)
- [x] Profile popup offscreen [https://github.com/threefoldtech/twin_aydo/issues/614](url)
